repos:
  - repo: https://github.com/pycqa/flake8
    rev: "3.9.2" # pick a git hash / tag to point to
    hooks:
      - id: flake8

  - repo: https://github.com/pycqa/pylint
    rev: v2.10.2
    hooks:
      - id: pylint
        args:
          - --errors-only
          - --max-line-length=88
          - --ignore-imports=yes
          - -d duplicate-code
          - --disable=F0401
          - --disable=E0611
          - --disable=E0401

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.961"
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [types-PyYAML, types-requests]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: check-ast
    # - id: check-yaml
    #   exclude: chart/spafe/templates/configmap.yaml
