repos:
  - repo: https://github.com/pycqa/flake8
    rev: "3.9.2" # pick a git hash / tag to point to
    hooks:
      - id: flake8

  - repo: https://github.com/pycqa/pylint
    rev: v2.10.2
    hooks:
      - id: pylint
        args:
          - --errors-only
          - --max-line-length=88
          - --ignore-imports=yes
          - -d duplicate-code
          - --disable=F0401
          - --disable=E0611
          - --disable=E0401
